cps_stuff/config/routes.rb
CpsStuff::Application.routes.draw do
  resources :request_items

  resources :schools

  resources :items

  resources :users

end

cps_stuff/app/models/item.rb
class Item < ActiveRecord::Base
end

cps_stuff/app/models/request_item.rb
class RequestItem < ActiveRecord::Base
end

cps_stuff/app/models/school.rb
class School < ActiveRecord::Base
end

cps_stuff/app/models/user.rb
class User < ActiveRecord::Base
end

cps_stuff/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

cps_stuff/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:school_id, :name, :category, :img)
    end
end

cps_stuff/app/controllers/request_items_controller.rb
class RequestItemsController < ApplicationController
  before_action :set_request_item, only: [:show, :edit, :update, :destroy]

  # GET /request_items
  # GET /request_items.json
  def index
    @request_items = RequestItem.all
  end

  # GET /request_items/1
  # GET /request_items/1.json
  def show
  end

  # GET /request_items/new
  def new
    @request_item = RequestItem.new
  end

  # GET /request_items/1/edit
  def edit
  end

  # POST /request_items
  # POST /request_items.json
  def create
    @request_item = RequestItem.new(request_item_params)

    respond_to do |format|
      if @request_item.save
        format.html { redirect_to @request_item, notice: 'Request item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @request_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @request_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_items/1
  # PATCH/PUT /request_items/1.json
  def update
    respond_to do |format|
      if @request_item.update(request_item_params)
        format.html { redirect_to @request_item, notice: 'Request item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @request_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_items/1
  # DELETE /request_items/1.json
  def destroy
    @request_item.destroy
    respond_to do |format|
      format.html { redirect_to request_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_item
      @request_item = RequestItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_item_params
      params.require(:request_item).permit(:school_id, :item_id, :user_id)
    end
end

cps_stuff/app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render action: 'show', status: :created, location: @school }
      else
        format.html { render action: 'new' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :address, :contact)
    end
end

cps_stuff/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

cps_stuff/app/helpers/application_helper.rb
module ApplicationHelper
end

cps_stuff/app/helpers/items_helper.rb
module ItemsHelper
end

cps_stuff/app/helpers/request_items_helper.rb
module RequestItemsHelper
end

cps_stuff/app/helpers/schools_helper.rb
module SchoolsHelper
end

cps_stuff/app/helpers/users_helper.rb
module UsersHelper
end

cps_stuff/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :school_id %><br>
    <%= f.number_field :school_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :img %><br>
    <%= f.text_field :img %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cps_stuff/app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

cps_stuff/app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Name</th>
      <th>Category</th>
      <th>Img</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.school_id %></td>
        <td><%= item.name %></td>
        <td><%= item.category %></td>
        <td><%= item.img %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

cps_stuff/app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

cps_stuff/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @item.school_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Img:</strong>
  <%= @item.img %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

cps_stuff/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CpsStuff</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

cps_stuff/app/views/request_items/_form.html.erb
<%= form_for(@request_item) do |f| %>
  <% if @request_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request_item.errors.count, "error") %> prohibited this request_item from being saved:</h2>

      <ul>
      <% @request_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :school_id %><br>
    <%= f.number_field :school_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cps_stuff/app/views/request_items/edit.html.erb
<h1>Editing request_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @request_item %> |
<%= link_to 'Back', request_items_path %>

cps_stuff/app/views/request_items/index.html.erb
<h1>Listing request_items</h1>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Item</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @request_items.each do |request_item| %>
      <tr>
        <td><%= request_item.school_id %></td>
        <td><%= request_item.item_id %></td>
        <td><%= request_item.user_id %></td>
        <td><%= link_to 'Show', request_item %></td>
        <td><%= link_to 'Edit', edit_request_item_path(request_item) %></td>
        <td><%= link_to 'Destroy', request_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request item', new_request_item_path %>

cps_stuff/app/views/request_items/new.html.erb
<h1>New request_item</h1>

<%= render 'form' %>

<%= link_to 'Back', request_items_path %>

cps_stuff/app/views/request_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @request_item.school_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @request_item.item_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @request_item.user_id %>
</p>

<%= link_to 'Edit', edit_request_item_path(@request_item) %> |
<%= link_to 'Back', request_items_path %>

cps_stuff/app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cps_stuff/app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

cps_stuff/app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Contact</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.address %></td>
        <td><%= school.contact %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

cps_stuff/app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

cps_stuff/app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @school.address %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @school.contact %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

cps_stuff/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cps_stuff/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

cps_stuff/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

cps_stuff/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

cps_stuff/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>